server:
  port: 8081

amq:
  broker-name: artemis-node1
  mqtt-port: 1884
  core-port: 61617
  host: localhost
  data-directory: target/artemis-data-node1
  cluster-enabled: true
  cluster-connection-name: artemis-cluster

repro:
  core-consumer-enabled: true
